== Programowanie synchroniczne
var file = io.readfile('...')

tutaj następuje zablokowanie

var value = lib.count(...)

io.readFileAsynch('file',function count(){})

== Programowanie reaktywne
io.readfile(wynik).then(http.get(wynik).then(io.write)

operacje wykonują się asynchronicznie w "workerze", 
program działa dalej

[1,2,3].foreach(...)
	.map(...)
	.filter(...)


. observer pattern
. Marble diagrams
https://dzone.com/articles/marble-diagrams-rxjava-operators, 
. Interaktywne diagramy http://rxmarbles.com/
. Obserwator (Obserwer, Subscriber) reaguje na zdarzenia (onNext, onEnter, onComplete) tematu (Subject, observable)
. http://reactivex.io/documentation/operators/flatmap.html

== Zadanie 1
Wizualizacja wyniku WikiSearch
Nazwa [link]
Nazwa [link]
Nazwa [link]

== Zadanie 2
Na ekranie przesuwa si kwadrat losowo co 1 sekunde w róznych kierunkach
Przeduwamy klawiszami drugim kwadratem po ekranie, mozna sprowować myszka.
Gdy kwadraty sie naloza to koniec gry.
Uzywać Rx do obslugi - strumienie (keyup, mouse)
